www/chapter_08/trends/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('future/', views.future, name='trends.future'),
    path('future/json/', views.futureJson, name='trends.future_json'),
]

www/chapter_08/property/forms.py
from django import forms
from django.core import validators
from django.core.validators import RegexValidator, EmailValidator

# tell python where to find module source code
import os,sys
#sys.path.append(os.path.realpath("../../../chapters/08/src"))
from config.config import Config
from booksomeplace.entity.base import Name, Location, Contact
from booksomeplace.entity.property import Property, PropInfo, RoomType
from booksomeplace.domain.partner import PartnerService
from booksomeplace.domain.property import PropertyService
from booksomeplace.domain.common import CommonService

"""
Name = {
    "title"    : <formal titles, e.g. Mr, Ms, Dr, etc.>,
    "first"    : <first name, also referred to as "given" name>,
    "middle"   : <middle name, optional>,
    "last"     : <last name, also referred to as "surname" or "family name">,
    "suffix"   : <any additional name information included after the last name>
}
"""
class NameForm(forms.Form) :
    # pull list of titles from common
    config    = Config()
    commonSvc = CommonService(config)
    titles    = [(item, item) for item in commonSvc.fetchByKey('title')]
    # define form fields
    alphaOnly   = RegexValidator(r'^[a-zA-Z]*$', 'Only letters are allowed.')
    name_title  = forms.ChoiceField(label='Title',choices=titles)
    name_first  = forms.CharField(label='First Name',validators=[alphaOnly])
    name_middle = forms.CharField(label='M.I.',required=False)
    name_last   = forms.CharField(label='Last Name',validators=[alphaOnly])
    name_suffix = forms.CharField(label='Suffix',required=False)

"""
PropInfo = {
    "type"        : <propertyType>,
    "chain"       : <chain>,
    "photos"      : <stored using GridFS>,
    "facilities"  : [<facilityType>,<facilityType>,etc.],
    "description" : <string>,
    "currency"    : <currencyType>,
    "taxFee"      : <float>
}
"""
class PropInfoForm(forms.Form) :
    # pull list of types from common
    config    = Config()
    commonSvc = CommonService(config)
    facTypes  = [(item, '... ' + item) for item in commonSvc.fetchByKey('facilityType')]
    propTypes = [(item, item) for item in commonSvc.fetchByKey('propertyType')]
    currTypes = [(item, item) for item in commonSvc.fetchByKey('currency')]
    # define validator
    alnumPunc = RegexValidator(r'^[\w\.\-\,\"\' ]+$',
                              'Only letters, numbers, spaces, quotes, commas and periods are allowed.')
    # define fields
    info_type       = forms.ChoiceField(label='Property Type',choices=propTypes)
    info_chain      = forms.CharField(label='Chain',validators=[validators.validate_slug],required=False)
    info_photos     = forms.URLField(label='Photo URL',required=False)
    info_facilities = forms.MultipleChoiceField(label='Facilities',choices=facTypes,
                                                widget=forms.CheckboxSelectMultiple(attrs={'class': 'check_horizontal'}))
    info_other_fac  = forms.CharField(label='Other Facilities',required=False)
    info_currency   = forms.ChoiceField(label='Currency',choices=currTypes)
    info_taxFee     = forms.FloatField(label='Taxes/Fees')
    info_description= forms.CharField(label='Description',validators=[alnumPunc],
                                      widget=forms.Textarea(attrs={'rows' : 4, 'cols' : 80}))

"""
Location = {
    "streetAddress"   : <number and name of street>,
    "buildingName"    : <name of building>,
    "floor"           : <number of name of the floor>,
    "roomAptCondoFlat": <room/apt/condo/flat number>,
    "city"            : <city name>,
    "stateProvince"   : <state or province>,
    "locality"        : <other local identifying information>,
    "country"         : <ISO2 country code>,
    "postalCode"      : <postal code>,
    "latitude"        : <latitude>,
    "longitude"       : <longitude>
}
"""
class LocationForm(forms.Form) :
    # define validator
    iso2 = RegexValidator(r'^[A-Z]{2}$', 'Country code must be a valid ISO2 code (2 letters UPPERCASE).')
    # define fields
    location_streetAddress    = forms.CharField(label ='Street Address')
    location_buildingName     = forms.CharField(label ='Building Name',required=False)
    location_floor            = forms.CharField(label ='Floor',required=False)
    location_roomAptCondoFlat = forms.CharField(label ='Room/Condo',required=False)
    location_city             = forms.CharField(label ='City')
    location_stateProvince    = forms.CharField(label ='State/Province')
    location_locality         = forms.CharField(label ='Locality',required=False)
    location_country          = forms.CharField(label ='Country',validators=[iso2])
    location_postalCode       = forms.CharField(label ='Postal Code')
    location_latitude         = forms.CharField(label ='Latitude')
    location_longitude        = forms.CharField(label ='Longitude')

"""
Contact = {
    "email"    : <primary email address>,
    "phone"    : <primary phone number>,
    "socMedia" : <preferred social media contact>,
}
"""
class ContactForm(forms.Form) :
    # pull list of types from common
    config    = Config()
    commonSvc = CommonService(config)
    socTypes  = [(item, item) for item in commonSvc.fetchByKey('socMediaType')]
    # define validator
    validEmail = EmailValidator(message="Must be a valid email address")
    # define fields
    contact_email    = forms.EmailField(label ='Email',validators=[validEmail])
    contact_phone    = forms.CharField(label='Phone')
    contact_soc_type = forms.ChoiceField(label='Social Media',choices=socTypes,required=False)
    contact_soc_addr = forms.CharField(label='Social Media Identity',required=False)

"""
RoomType = {
    "roomTypeKey"  : <string>,
    "type"         : <roomType>,
    "view"         : <string>,
    "description"  : <string>,
    "beds"         : [<bedType>,<bedType>,etc.],
    "numAvailable" : <int>,
    "numBooked"    : <int>,
    "price"        : <float>
}
"""
class RoomTypeForm(forms.Form) :
    # pull list of types from common
    config    = Config()
    commonSvc = CommonService(config)
    roomTypes = [(item, item) for item in commonSvc.fetchByKey('roomType')]
    bedTypes  = [(item, item) for item in commonSvc.fetchByKey('bedType')]
    # define validator
    alnumPunc = RegexValidator(r'^[\w\.\-\,\"\' ]+$',
                              'Only letters, numbers, spaces, quotes, commas and periods are allowed.')
    # define fields
    room_type_type         = forms.ChoiceField(label='Room Type',choices=roomTypes)
    room_type_view         = forms.CharField(label='View',validators=[alnumPunc])
    room_type_description  = forms.CharField(label='Description',
                                             widget=forms.Textarea(attrs={'rows' : 2, 'cols' : 40}),
                                             validators=[alnumPunc])
    room_type_beds         = forms.MultipleChoiceField(label='Bed Types',choices=bedTypes,
                                               widget=forms.CheckboxSelectMultiple(attrs={'class':'check_horizontal'}))
    room_type_numAvailable = forms.IntegerField(label='How Many?')
    room_type_price        = forms.FloatField(label='Price (USD)')

"""
Property = {
    "propertyKey" : <string>,
    "partnerKey"  : <string>,
    "propName"    : <name of this property>,
    "propInfo"    : <PropInfo>,
    "address"     : <Location>,
    "contactName" : <Name>,
    "contactInfo" : <Contact>,
    "rooms"       : [<RoomType>,<RoomType>,etc.],
    "reviews"     : [<Review>,<Review>,etc.],
    "rating"      : <int>,
    "totalBooked" : <int>
}
"""
class PropertyForm(forms.Form) :
    config      = Config()
    partSvc     = PartnerService(config)
    partKeys    = partSvc.fetchPartnerKeys()
    # define validator
    alnumPunc = RegexValidator(r'^[\w\.\-\,\"\' ]+$',
                              'Only letters, numbers, spaces, quotes, commas and periods are allowed.')
    # define fields
    prop_partnerKey = forms.ChoiceField(label='Partner',choices=partKeys)
    prop_propName   = forms.CharField(label='Property Name',validators=[alnumPunc])

"""
Choose the partner you want to work with
"""
class ChoosePartnerForm(forms.Form) :
    partSvc     = PartnerService(Config())
    partKeys    = partSvc.fetchPartnerKeys()
    # define validator
    alnumPunc = RegexValidator(r'^[\w\.\-\,\"\' ]+$',
                              'Only letters, numbers, spaces, quotes, commas and periods are allowed.')
    # define fields
    prop_partnerKey = forms.ChoiceField(label='Partner',choices=partKeys)

class FormService() :

    forms = {}
    list_fields = ['info_facilities','room_type_beds']

    def __init__(self) :
        self.forms.update({ 'prop' : PropertyForm() })
        self.forms.update({ 'name' : NameForm() })
        self.forms.update({ 'info' : PropInfoForm() })
        self.forms.update({ 'contact' : ContactForm() })
        self.forms.update({ 'location' : LocationForm() })

    def getForm(self, key) :
        if key in self.forms :
            return self.forms[key]
        else :
            return None

    """
    Hydrates form from POST data
    @param dict request.POST
    """
    def hydrateFormsFromPost(self, data) :
        self.forms['prop'] = PropertyForm(self.getDataByKey('prop', data))
        self.forms['name'] = NameForm(self.getDataByKey('name', data))
        self.forms['info'] = PropInfoForm(self.getDataByKey('info', data))
        self.forms['contact'] = ContactForm(self.getDataByKey('contact', data))
        self.forms['location'] = LocationForm(self.getDataByKey('location', data))

    """
    Filters request.POST data so that only form fields with the prefix are returned
    @param string key == form key
    @param dict request.POST
    @return dict formData
    """
    def getDataByKey(self, key, data) :
        prefix = key + '_'
        formData = {}
        for field, value in data.items() :
            if field[0:len(prefix)] == prefix :
                if field in self.list_fields :

www/chapter_08/trends/forms.py
from django import forms
from django.core import validators
from django.core.validators import RegexValidator

"""
Request user input on key fields representing property location
"""
class TrendForm(forms.Form) :

    # define fields
    trend_city     = forms.CharField(label='City',required=False)
    trend_region   = forms.CharField(label='Region',required=False)
    trend_locality = forms.CharField(label='Locality',required=False)
    trend_country  = forms.CharField(label='Country',required=False,widget=forms.TextInput(attrs={'size':'2','maxlength':'2'}))
    trend_factor   = forms.DecimalField(label='Factor',required=False,initial=.10,widget=forms.NumberInput(attrs={'step':.01}))

www/chapter_08/trends/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from .forms import TrendForm

# tell python where to find module source code
import os,sys
#sys.path.append(os.path.realpath("../../../chapters/08/src"))
from config.config import Config
from booksomeplace.domain.booking import BookingService

"""
This view method sets up the screen for the future trends report
@param request
@return HTML
"""
def future(request) :

    # build master form
    params = {
        'trend_city'     : None,
        'trend_region'   : 'England',
        'trend_locality' : None,
        'trend_country'  : 'GB',
        'trend_factor'   : .10,
    }
    context = { 'form' : TrendForm(initial=params) }
    trend_master = render_to_string('trend.html', context)

    # embed form in layout
    page = render_to_string('layout.html', {'contents' : trend_master})
    return HttpResponse(page)

"""
This view method returns a list of revenue totals for 12 months:
6 months - today + 6 months
@param request
@return JSON list
"""
def futureJson(request) :

    # init vars
    import json
    bookSvc = BookingService(Config())
    params  = {
        'trend_city'     : None,
        'trend_region'   : 'England',
        'trend_locality' : None,
        'trend_country'  : 'GB',
        'trend_factor'   : 0.10
    }

    # if this is a POST request process the form data
    if request.method == 'POST':
        params = request.POST

    # get trend data from booking service
    data = bookSvc.getTrendData(params)
    return HttpResponse(json.dumps(data), content_type='application/json')

www/chapter_08/templates/property_choose_partner.html
{% load static %}
<style>
.check_horizontal {
    list-style: none;
    display: inline-flex;
    margin-left: -40px;
}
li label,input {
    display:block;
    margin-right: 20px;
}
.extra {
    padding-bottom: 20px;
}
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #BFBFBF;">
    <div class="container" style="margin-top: -100px;">
        <form action="/property/edit/" method="post">
            {% csrf_token %}
            <h1>Update Property Contact</h1>
            Name of Property: {{ prop_name }}
            <div class="row extra" style="background-color: #E6E6FA;">
                <div class="col-md-6">
                    {{ name_form_html }}
                </div><!-- end col -->
                <div class="col-md-6" style="background-color: #D6D6F0;">
                    {{ contact_form_html }}
                </div><!-- end col -->
            </div><!-- end row -->
        <input type="submit" value="Submit">
        </form>
        {{ message }}
    </div><!-- end container -->
</section><!-- end section -->

www/chapter_08/templates/property_choose_partner_and_property.html
{% load static %}
<style>
.check_horizontal {
    list-style: none;
    display: inline-flex;
    margin-left: -40px;
}
li label,input {
    display:block;
    margin-right: 20px;
}
.extra {
    padding-bottom: 20px;
}
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #BFBFBF;">
    <div class="container" style="margin-top: -100px;">
        <form action="{{ action }}" method="post">
            {% csrf_token %}
            <h1>Choose Partner and Property</h1>
            <div class="row extra" style="background-color: #E6E6FA;">
                <div class="col-md-6">
                    {{ choose_partner_form }}
                </div><!-- end col -->
                <div class="col-md-6" style="background-color: #D6D6F0;">
                    {{ choose_property_form }}
                </div><!-- end col -->
            </div><!-- end row -->
        <input type="submit" value="Submit">
        </form>
        {{ message }}
    </div><!-- end container -->
</section><!-- end section -->

www/chapter_08/templates/property_list.html
{% load static %}
<style>
    .check_horizontal {
        list-style: none;
        display: inline-flex;
        margin-left: -40px;
    }
    li label,input {
        display:block;
        margin-right: 20px;
    }
    .extra {
        padding-bottom: 20px;
    }
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #E5E5E5;">
    <div class="container" style="margin-top: -100px;">
        <div class="row">
            <div class="col-md-6">
                <h1>Property Listing</h1>
                <div class="row extra">
                    <div class="col-md-2"><b>Name</b></div>
                    <div class="col-md-4">{{ prop_name }}</div>
                </div><!-- end row -->
                <div class="row extra">
                    <div class="col-md-2"><b>Type</b></div>
                    <div class="col-md-4">{{ prop_type }}</div>
                </div><!-- end row -->
                <div class="row extra">
                    <div class="col-md-2"><b>Description</b></div>
                    <div class="col-md-4">{{ prop_des }}</div>
                </div><!-- end row -->
            </div>
            <div class="col-md-6">
                <img src="{% static 'images/hotel_korat_jun_2019.jpg' %}" style="width:100%;"/>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
            <h3>Room Types</h3>
            <table id="data_table" class="display" width="100%">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>View</th>
                        <th>Beds</th>
                        <th>Available</th>
                        <th>Info</th>
                    </tr>
                </thead>
            </table>
            {{ message }}
            </div>
        </div><!-- end row -->
    </div><!-- end container -->
</section><!-- end section -->

{% block extra_head %}
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock %}
<script type="text/javascript" charset="utf8">
$(document).ready( function () {
    $.ajax({
        'type'     : 'GET',
        'url'      : '/property/json/rooms/{{ prop_key }}/',
        'dataType' : 'json',
        'success'  : function(data){
            $.each(data, function(i,row) {
                item = '<tr><td>' + row.type + '</td>'
                item += '<td>' + row.view + '</td>'
                item += '<td>' + row.beds + '</td>'
                item += '<td>' + row.available + '</td>'
                item += '<td>' + row.link + '</td></tr>'
                $('#data_table').append(item);
            });
        }
    });
});
</script>

www/chapter_08/templates/property_list_del.html
{% load static %}
<style>
    .check_horizontal {
        list-style: none;
        display: inline-flex;
        margin-left: -40px;
    }
    li label,input {
        display:block;
        margin-right: 20px;
    }
    .extra {
        padding-bottom: 20px;
    }
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #E5E5E5;">
    <div class="container" style="margin-top: -100px;">
        <form method="post">
        {% if not confirm %}
        <div class="row extra" style="background-color: #C8C8EE;">
            <h1>Choose Partner and Property to Delete</h1>
            <div class="col-md-4">
                {{ choose_part_form }}
            </div><!-- end col -->
            <div class="col-md-4">
                <label>Property:</label>
                <select name="prop_propertyKey" id="ddlProperties" >
                    <option value="0">Choose Partner First</option>
                </select>
            </div><!-- end col -->
            <div class="col-md-4">
                <input type="submit" name="del_confirm_choose" value="Choose" />
            </div><!-- end col -->
        </div><!-- end row -->
        {% else %}
        <div class="row extra" style="background-color: #FDEEEC;">
            <h1>Confirm Deletion</h1>
            <div class="col-md-6">
                <div class="row extra">
                    <div class="col-md-2"><b>Name</b></div>
                    <div class="col-md-4">{{ prop_name }}</div>
                </div><!-- end row -->
                <div class="row extra">
                    <div class="col-md-2"><b>Type</b></div>
                    <div class="col-md-4">{{ prop_type }}</div>
                </div><!-- end row -->
                <div class="row extra">
                    <div class="col-md-2"><b>Description</b></div>
                    <div class="col-md-4">{{ prop_des }}</div>
                </div><!-- end row -->
                <div class="row extra">
                    <div class="col-md-4"><b>DELETE?</b></div>
                    <div class="col-md-2">
                        <input type="submit" name="del_confirm_yes" value="Yes" />
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="del_confirm_no" value="No" />
                        <input type="hidden" name="prop_key" value="{{ prop_key }}" />
                    </div>
                </div><!-- end row -->
            </div>
            <div class="col-md-6">
                <img src="{% static 'images/hotel_korat_jun_2019.jpg' %}" style="width:100%;"/>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
            {{ message }}
            </div>
        </div><!-- end row -->
        </form>
    </div><!-- end container -->
</section><!-- end section -->

{% block extra_head %}
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock %}
<script type="text/javascript" charset="utf8">
$(document).ready(function() {
    $("#id_prop_partnerKey").change(function() {
        var partKey = $(this).val();
        console.log( "partner key: " + partKey );
        $("#ddlProperties").empty();
        $.ajax({
            type: "GET",
            url: "/property/json/by_part/" + partKey + "/",
            dataType: 'json',
            success: function(data){
                // Parse the returned json data
                $.each(data, function(i, d) {
                    $("#ddlProperties").append(
                        '<option value="' + d.propertyKey + '">'
                        + d.propName
                        + '</option>');
                });
            }
        });
    });
    $("#ddlProperties").change(function() {
        var propKey = $(this).val();
        console.log( "property key: " + propKey );
        $.ajax({
            type: "GET",
            url: "/property/json/update_contact/" + propKey + "/",
            dataType: 'json',
            success: function(data){
                $("#id_name_title").val(data['contactName']['title']);
                $("#id_name_first").val(data['contactName']['first']);
                $("#id_name_last").val(data['contactName']['last']);
                $("#id_name_suffix").val(data['contactName']['suffix']);
                $("#id_contact_email").val(data['contactInfo']['email']);
                $("#id_contact_phone").val(data['contactInfo']['phone']);
                var socMedia = data['contactInfo']['socMedia'];
                for (var k in socMedia) {
                    $("#id_contact_soc_type").val(k);
                    $("#id_contact_soc_addr").val(socMedia[k]);
                }
            }
        });
    });
});
</script>

www/chapter_08/templates/property_prop.html
    {% load static %}
    <h3>Property Name</h3>
    <div class="row">
        <div class="col-md-4">{{ form.prop_partnerKey.label_tag }}</div>
        <div class="col-md-4">{{ form.prop_partnerKey }}</div>
        <div class="col-md-4">{{ form.prop_partnerKey.errors }}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{ form.prop_propName.label_tag }}</div>
        <div class="col-md-4">{{ form.prop_propName }}</div>
        <div class="col-md-4">{{ form.prop_propName.errors }}</div>
    </div>

www/chapter_08/templates/property_update_contact.html
{% load static %}
<style>
    .check_horizontal {
        list-style: none;
        display: inline-flex;
        margin-left: -40px;
    }
    li label,input {
        display:block;
        margin-right: 20px;
    }
    .extra {
        padding-bottom: 20px;
    }
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #BFBFBF;">
    <div class="container" style="margin-top: -100px;">
        <form action="/property/contact/update/" method="post">
            {% csrf_token %}
            <h1>Update Property Contact</h1>
            <div class="row extra" style="background-color: #C8C8EE;">
                <div class="col-md-6">
                    {{ choose_part_form }}
                </div><!-- end col -->
                <div class="col-md-6">
                    <label>Property:</label>
                    <select name="prop_propertyKey" id="ddlProperties" >
                        <option value="0">Choose Partner First</option>
                    </select>
                </div><!-- end col -->
            </div><!-- end row -->
            <div class="row extra" style="background-color: #E6E6FA;">
                <div class="col-md-6">
                    {{ name_form_html }}
                </div><!-- end col -->
                <div class="col-md-6" style="background-color: #D6D6F0;">
                    {{ contact_form_html }}
                </div><!-- end col -->
            </div><!-- end row -->
        <input type="submit" value="Submit">
        </form>
        {{ message }}
    </div><!-- end container -->
</section><!-- end section -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
$(document).ready(function() {
    $("#id_prop_partnerKey").change(function() {
        var partKey = $(this).val();
        console.log( "partner key: " + partKey );
        $("#ddlProperties").empty();
        $.ajax({
            type: "GET",
            url: "/property/json/by_part/" + partKey + "/",
            dataType: 'json',
            success: function(data){
                // Parse the returned json data
                $.each(data, function(i, d) {
                    $("#ddlProperties").append(
                        '<option value="' + d.propertyKey + '">'
                        + d.propName
                        + '</option>');
                });
            }
        });
    });
    $("#ddlProperties").change(function() {
        var propKey = $(this).val();
        console.log( "property key: " + propKey );
        $.ajax({
            type: "GET",
            url: "/property/json/update_contact/" + propKey + "/",
            dataType: 'json',
            success: function(data){
                $("#id_name_title").val(data['contactName']['title']);
                $("#id_name_first").val(data['contactName']['first']);
                $("#id_name_last").val(data['contactName']['last']);
                $("#id_name_suffix").val(data['contactName']['suffix']);
                $("#id_contact_email").val(data['contactInfo']['email']);
                $("#id_contact_phone").val(data['contactInfo']['phone']);
                var socMedia = data['contactInfo']['socMedia'];
                for (var k in socMedia) {
                    $("#id_contact_soc_type").val(k);
                    $("#id_contact_soc_addr").val(socMedia[k]);
                }
            }
        });
    });
});
</script>

www/chapter_08/templates/trend.html
{% load static %}
<style>
    li label,input {
        display:block;
        margin-right: 20px;
    }
    .extra {
        padding-bottom: 20px;
    }
</style>
<section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="background-color: #E5E5E5;">
    <div class="container" style="margin-top: -100px;">
        <div class="row">
            <div class="col-md-12">
                <h1>Future Revenue Trends by Property Location</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                    <h3>Enter Trend Data</h3>
                    <form action="/trends/future/" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-3">{{ form.trend_city.label_tag }}</div>
                        <div class="col-md-4">{{ form.trend_city }}</div>
                        <div class="col-md-4">{{ form.trend_city.errors }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">{{ form.trend_region.label_tag }}</div>
                        <div class="col-md-4">{{ form.trend_region }}</div>
                        <div class="col-md-4">{{ form.trend_region.errors }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">{{ form.trend_locality.label_tag }}</div>
                        <div class="col-md-4">{{ form.trend_locality }}</div>
                        <div class="col-md-4">{{ form.trend_locality.errors }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">{{ form.trend_country.label_tag }}</div>
                        <div class="col-md-4">{{ form.trend_country }}</div>
                        <div class="col-md-4">{{ form.trend_country.errors }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">{{ form.trend_factor.label_tag }}</div>
                        <div class="col-md-4">{{ form.trend_factor }}</div>
                        <div class="col-md-4">{{ form.trend_factor.errors }}</div>
                    </div>
                    <input type="submit" value="Refresh" />
                    </form>
                    Make changes to the report parameters to update the chart
                    </div>
                </div><!-- end row -->
            </div>
            <div class="col-md-6">
                <div class="ct-chart ct-perfect-fourth"></div>
            </div>
        </div>
    </div><!-- end container -->
</section><!-- end section -->

{% block extra_head %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
<style>
.ct-label {
    color: black;
    font-weight: bold;
    font-size: 9pt;
}
</style>
{% endblock %}
<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" charset="utf8">
// CREDITS: JavaScript provided by chartist.js (http://gionkunz.github.io/chartist-js/index.html)
// LICENSE: MIT license (no strings attached, no restrictions)
// data: { labels: [x,y,z], series: [1,2,3] }
function doChart(data)
{
    var plot = { labels:data.labels, series:data.series };
    new Chartist.Line('.ct-chart', plot);
}
function ajaxCall()
{
    $.ajax({
        type: "POST",
        url: "/trends/future/json/",
        dataType: 'json',
        data: {
            'trend_city'     : $('#id_trend_city').val() ,
            'trend_region'   : $('#id_trend_region').val() ,
            'trend_locality' : $('#id_trend_locality').val() ,
            'trend_country'  : $('#id_trend_country').val() ,
            'trend_factor'   : $('#id_trend_factor').val() ,
        },
        success: function (data) {
            //data = $.parseJSON(data);
            console.log("request succeeded");
            console.log(data);
            doChart(data);
        }
    });
}
$(document).ready(function() {
    ajaxCall();
    $("#id_trend_city").change(function() { ajaxCall(); });
    $("#id_trend_region").change(function() { ajaxCall(); });
    $("#id_trend_locality").change(function() { ajaxCall(); });
    $("#id_trend_country").change(function() { ajaxCall(); });
    $("#id_trend_factor",).change(function() { ajaxCall(); });
});
</script>